In [1]:
import pandas as pd
from natsort import natsorted

API_KEY = 'AIzaSyBsgzZAireGJP-F5k97lvMghO3qXWdFZac'
SHEET_ID = '1wq-iHEoNbcY1DJIHjkFCTgbQCaRLFwcjJScZs1GJoYI'
TEMPLATE_TAB = 'https://docs.google.com/spreadsheets/d/{SHEET}/gviz/tq?tqx=out:csv&sheet={TAB}'
TEMPLATE_GID = 'https://docs.google.com/spreadsheets/d/{SHEET}/export?format=csv&id={SHEET}&gid={GID}'

In [2]:
TAB='CODE_V0.5'
df_codeV5 = pd.read_csv( TEMPLATE_TAB.format(SHEET=SHEET_ID,TAB=TAB) )
df_codeV5.head()

,Unnamed: 0,Unnamed: 1,Weights Vector:,"2,0.5,1,1,1,1,1,1,1,1,0.5,0.5,0.5,2,1,1,1,0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,0.5,1,1,1,1,1,1,1,1,1,1,1",Code value (hide),Weight,Appendix line drawings:,Draft Document:,Table:,Matrix: (Need to check *all* matrices for number maxes),Unnamed: 10
0,A1\n Shape,0,Too broken to code,A1.0 Too broken to code,0,2.0,NaN,NaN,NaN,NaN,NaN
1,NaN,1,Spine,A1.1 Spine,1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2,Cruciform,A1.2 Cruciform,2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3,Circular or oval,A1.3 Circular or oval,3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,4,Spade,A1.4 Spade,4,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_codeV5.iloc[:, 0] = df_codeV5.iloc[:, 0].ffill()
df_codeV5[['codegroup', 'codegroup_name']] = df_codeV5.iloc[:, 0].str.split(n=1,expand=True)
df_codeV5['code_idx'] = df_codeV5.iloc[:, 1]
df_codeV5['code'] = df_codeV5['codegroup']+'.'+df_codeV5['code_idx'].astype(str)
df_codeV5['code_text'] = df_codeV5.iloc[:, 2]
df_codeV5['full_label'] = df_codeV5['code'] + ' ' + df_codeV5['codegroup_name'] + ': ' + df_codeV5['code_text']
df_codeV5['weight'] = df_codeV5['Weight'].ffill()
df_codeV5.loc[ df_codeV5['codegroup']=='Z1','weight'] = pd.NA
df_codeV5 = df_codeV5[['codegroup','code_idx','code','codegroup_name','code_text','full_label','weight']]

In [4]:
df_codeV5

,codegroup,code_idx,code,codegroup_name,code_text,full_label,weight
0,A1,0,A1.0,Shape,Too broken to code,A1.0 Shape: Too broken to code,2.0
1,A1,1,A1.1,Shape,Spine,A1.1 Shape: Spine,2.0
2,A1,2,A1.2,Shape,Cruciform,A1.2 Shape: Cruciform,2.0
3,A1,3,A1.3,Shape,Circular or oval,A1.3 Shape: Circular or oval,2.0
4,A1,4,A1.4,Shape,Spade,A1.4 Shape: Spade,2.0
...,...,...,...,...,...,...,...
278,O10,2,O10.2,Mound,Mounded,O10.2 Mound: Mounded,1.0
279,Z1,1,Z1.1,Ichthyolith Type,Tooth,Z1.1 Ichthyolith Type: Tooth,NaN
280,Z1,2,Z1.2,Ichthyolith Type,Denticle,Z1.2 Ichthyolith Type: Denticle,NaN
281,Z1,3,Z1.3,Ichthyolith Type,Other microfossil,Z1.3 Ichthyolith Type: Other microfossil,NaN
282,Z1,4,Z1.4,Ichthyolith Type,Excess image/artifact,Z1.4 Ichthyolith Type: Excess image/artifact,NaN

In [5]:
cats = dict()
for name, group in natsorted(df_codeV5.groupby('codegroup')):
    cats[name] = natsorted(list(group.code))
cats

{'A1': ['A1.0',
  'A1.1',
  'A1.2',
  'A1.3',
  'A1.4',
  'A1.5',
  'A1.6',
  'A1.7',
  'A1.8',
  'A1.9'],
 'A2': ['A2.0', 'A2.1', 'A2.2', 'A2.3', 'A2.4', 'A2.5', 'A2.6'],
 'B1': ['B1.0', 'B1.1', 'B1.2', 'B1.3', 'B1.4'],
 'B2': ['B2.0', 'B2.1', 'B2.2', 'B2.3', 'B2.4'],
 'B3': ['B3.0', 'B3.1', 'B3.2'],
 'C1': ['C1.0', 'C1.1', 'C1.2', 'C1.3', 'C1.4'],
 'C2': ['C2.0', 'C2.1', 'C2.2', 'C2.3', 'C2.4'],
 'C3': ['C3.0', 'C3.1', 'C3.2'],
 'D1': ['D1.0', 'D1.1', 'D1.2', 'D1.3', 'D1.4'],
 'E1': ['E1.0',
  'E1.1',
  'E1.2',
  'E1.3',
  'E1.4',
  'E1.5',
  'E1.6',
  'E1.7',
  'E1.8',
  'E1.9',
  'E1.10',
  'E1.11'],
 'E2': ['E2.0', 'E2.1', 'E2.2', 'E2.3'],
 'E3': ['E3.0', 'E3.1', 'E3.2', 'E3.3', 'E3.4'],
 'E4': ['E4.0', 'E4.1', 'E4.2', 'E4.3'],
 'F1': ['F1.0', 'F1.1', 'F1.2', 'F1.3', 'F1.4', 'F1.5', 'F1.6'],
 'G1': ['G1.0',
  'G1.1',
  'G1.2',
  'G1.3',
  'G1.4',
  'G1.5',
  'G1.6',
  'G1.7',
  'G1.8'],
 'G2': ['G2.0', 'G2.1', 'G2.2', 'G2.3', 'G2.4', 'G2.5', 'G2.6', 'G2.7'],
 'G3': ['G3.0', 'G3.1', 'G3.2', 'G3.3'],
 'H1': ['H1.0',
  'H1.1',
  'H1.2',
  'H1.3',
  'H1.4',
  'H1.5',
  'H1.6',
  'H1.7',
  'H1.8'],
 'I1': ['I1.0', 'I1.1', 'I1.2', 'I1.3', 'I1.4'],
 'I2': ['I2.0', 'I2.1', 'I2.2', 'I2.3'],
 'I3': ['I3.0', 'I3.1', 'I3.2', 'I3.3', 'I3.4', 'I3.5', 'I3.6'],
 'J1': ['J1.0', 'J1.1', 'J1.2', 'J1.3', 'J1.4', 'J1.5'],
 'J2': ['J2.0', 'J2.1', 'J2.2', 'J2.3', 'J2.4', 'J2.5', 'J2.6'],
 'K1': ['K1.0',
  'K1.1',
  'K1.2',
  'K1.3',
  'K1.4',
  'K1.5',
  'K1.6',
  'K1.7',
  'K1.8',
  'K1.9',
  'K1.10',
  'K1.11'],
 'K2': ['K2.0', 'K2.1', 'K2.2', 'K2.3', 'K2.4'],
 'L1': ['L1.0', 'L1.1', 'L1.2', 'L1.3', 'L1.4', 'L1.5'],
 'L2': ['L2.0', 'L2.1', 'L2.2', 'L2.3', 'L2.4'],
 'L3': ['L3.0', 'L3.1', 'L3.2', 'L3.3'],
 'L4': ['L4.0', 'L4.1', 'L4.2', 'L4.3', 'L4.4', 'L4.5'],
 'M1': ['M1.0', 'M1.1', 'M1.2', 'M1.3', 'M1.4', 'M1.5', 'M1.6', 'M1.7'],
 'M2': ['M2.0', 'M2.1', 'M2.2', 'M2.3'],
 'M3': ['M3.0', 'M3.1', 'M3.2', 'M3.3'],
 'M4': ['M4.0', 'M4.1', 'M4.2', 'M4.3', 'M4.4', 'M4.5', 'M4.6', 'M4.7'],
 'N1': ['N1.0',
  'N1.1',
  'N1.2',
  'N1.3',
  'N1.4',
  'N1.5',
  'N1.6',
  'N1.7',
  'N1.8'],
 'N2': ['N2.0', 'N2.1', 'N2.2', 'N2.3', 'N2.4', 'N2.5', 'N2.6', 'N2.7'],
 'N3': ['N3.0', 'N3.1', 'N3.2', 'N3.3'],
 'O1': ['O1.0',
  'O1.1',
  'O1.2',
  'O1.3',
  'O1.4',
  'O1.5',
  'O1.6',
  'O1.7',
  'O1.8',
  'O1.9',
  'O1.10',
  'O1.11',
  'O1.12'],
 'O2': ['O2.0', 'O2.1', 'O2.2', 'O2.3', 'O2.4'],
 'O3': ['O3.0', 'O3.1', 'O3.2', 'O3.3'],
 'O4': ['O4.0', 'O4.1', 'O4.2', 'O4.3', 'O4.4', 'O4.5', 'O4.6', 'O4.7'],
 'O5': ['O5.0', 'O5.1', 'O5.2', 'O5.3', 'O5.4', 'O5.5'],
 'O6': ['O6.0', 'O6.1', 'O6.2', 'O6.3'],
 'O7': ['O7.0', 'O7.1', 'O7.2', 'O7.3', 'O7.4'],
 'O8': ['O8.0', 'O8.1', 'O8.2', 'O8.3', 'O8.4'],
 'O9': ['O9.0', 'O9.1', 'O9.2', 'O9.3'],
 'O10': ['O10.0', 'O10.1', 'O10.2'],
 'Z1': ['Z1.1', 'Z1.2', 'Z1.3', 'Z1.4']}

In [6]:
codegroups = natsorted(set(df_codeV5['codegroup']))
codegroups.insert(0, codegroups.pop(-1))  # put Z1 at the start
print(' '.join(codegroups))
print(len(codegroups))

Z1 A1 A2 B1 B2 B3 C1 C2 C3 D1 E1 E2 E3 E4 F1 G1 G2 G3 H1 I1 I2 I3 J1 J2 K1 K2 L1 L2 L3 L4 M1 M2 M3 M4 N1 N2 N3 O1 O2 O3 O4 O5 O6 O7 O8 O9 O10
47

In [7]:
TAB = 'Unique Types'
GID = '599510955'
types = pd.read_csv( TEMPLATE_GID.format(SHEET=SHEET_ID,GID=GID))
types['dropdown menu'] = types['dropdown menu'].fillna('NA')
assert len(types),len(set(types['dropdown menu']))
types

,dropdown menu,Associated Gross Type,Gross Type Dropdown
0,Airplane,"Arrowheads, Airplanes, Diamonds, and Triangles",Other Meandering
1,Angular Edged Diamond,"Arrowheads, Airplanes, Diamonds, and Triangles",Multi and Single Dimpled Complex Polygons
2,Angular Straight Edge,"Arrowheads, Airplanes, Diamonds, and Triangles",Bilateral Crowns
3,Arrowhead,"Arrowheads, Airplanes, Diamonds, and Triangles",Kites
4,Asymmetrical Criss Cross,Other Geometric,Other Geometric
...,...,...,...
182,Wrapped Trident,Tridents,NaN
183,Wrinkly,Other Meandering,NaN
184,Wrinkly Kite,Kites,NaN
185,z,NaN,NaN
186,Zebra Hoof,Other Linear,NaN

In [9]:
nested = {}
for name1, group1 in types.groupby('Associated Gross Type', dropna=False):
        if pd.isna(name1):
            for elem in list(group1['dropdown menu']):
                if pd.isna(elem): elem = 'NA'
                nested[elem] = None
        else:
            nested[name1] = {}
            for elem in list(group1['dropdown menu']):
                 nested[name1][elem] = None
nested

{'Arrowheads, Airplanes, Diamonds, and Triangles': {'Airplane': None,
  'Angular Edged Diamond': None,
  'Angular Straight Edge': None,
  'Arrowhead': None,
  'Bilateral Single Ridged Arrowhead': None,
  'Central Ridged Diamond': None,
  'Central Ridged Triangle': None,
  'Complex Central Ridged Triangle': None,
  'Cruciform Arrow': None,
  'Extended Forked Arrow': None,
  'Flying squirrel': None,
  'Funky Central Ridged Diamond': None,
  'Geometric Arrowhead': None,
  'High Ridged Diamond': None,
  'Short Troughed Diamond': None,
  'Stretched Airplane': None,
  'Triangular Troughed Arrow': None,
  'Troughed Diamond': None},
 'Bilateral Crowns': {'Bilateral Fan': None,
  'Bilateral Single Ridged': None,
  'Stretched Bilateral Central Ridged': None},
 'Criss Cross': {'Five Ridged Criss Cross': None,
  'Symmetrical Criss Cross': None},
 'Kites': {'Asymmetrical Kite with Oval Center': None,
  'Asymmetrical Kite with Ridged Mound': None,
  'Diamond Kite': None,
  'Generic Kite': None,
  'Kite with Bubble': None,
  'Kite-Like': None,
  'Sharp Kite': None,
  'Single Dimpled Quadrilateral': None,
  'Square Kite with Nodules': None,
  'Squished Kite': None,
  'Thin Ridged Kite': None,
  'Wrinkly Kite': None},
 'Linear Branching': {'Branching Dust Pan': None,
  'Branching Fan': None,
  'Branching Triangle': None,
  'Five Thin Ridged Branching Fan': None,
  'Oblong Branching Crown': None,
  'Shallow Ridged Branching Fan': None,
  'Stretched Branching Crown': None,
  'Widespread Branching Crown': None,
  'Wishbone': None},
 'Many Ridged Fans and Spades': {'Five Thin Ridged Fan': None,
  'Forked Spade': None,
  'Many Ridged Linear Fan': None,
  'Many Thin Ridged Spade ': None,
  'Rake': None,
  'Shallow Ridged Wide Crown': None,
  'Three Ridged Linear Fan with Ridge Outgrowths': None},
 'Multi and Single Dimpled Complex Polygons': {'Bilateral Polygon': None,
  'Bunny Ears': None,
  'Double Dimpled Hexagon': None,
  'Eyeball': None,
  'Fusiform Dimpled Diamond': None,
  'Generic Double Dimpled Complex Polygon': None,
  'Generic Single Dimpled Complex Polygon': None,
  'Helter Skelter': None,
  'Many Celled': None,
  'Many Celled Central Complex Polygon': None,
  'Raised Dimple': None,
  'Rounded Cone': None,
  'Single Dimpled Heptagon': None,
  'Single Dimpled Hexagon': None,
  'Single Dimpled Hexagon with Serrated Edges': None,
  'Single Dimpled Octagon': None,
  'Single Dimpled Pentagon': None,
  'Stretched Two Dimpled Spade': None,
  'Triple Dimpled Crown': None,
  'Two Dimpled Fan': None,
  'Two Dimpled Fan with Tail': None,
  'Two Dimpled Rectangle': None},
 'Other Branching': {'Branching Fragment': None},
 'Other Geometric': {'Asymmetrical Criss Cross': None, 'GenGeo': None},
 'Other Linear': {'Crinkle Tops': None,
  'Elephant': None,
  'Forked Oval': None,
  'Four Ridged Linear Spade': None,
  'Funky Central Ridged Spade': None,
  'GenLin': None,
  'Llama': None,
  'Single Ridged Spade': None,
  'Wilted tulip': None,
  'Zebra Hoof': None},
 'Other Meandering': {'Branching and Flared Chunk': None,
  'Oak Leaf': None,
  'Wrinkly': None},
 'Petals': {'Bottom Bulbed Three Ridged Petal': None,
  'Central Ridged Petal': None,
  'Central Troughed Petal': None,
  'Extended Central Long Troughed Petal': None,
  'Extended Central Troughed Petal': None,
  'Four Thin Ridged Petal': None,
  'Madeleine': None,
  'Many Ridged Petal': None,
  'Minnie Indented Shell': None,
  'Stretched Minnie Indented Shell': None,
  'Tall Central Ridged Petal': None,
  'Three Ridged Petal': None,
  'Triple Ridged Petal': None},
 'Ridged Circles': {'Central Ridged Textured Circle': None,
  'Circular Petal': None,
  'Minnie Ridged Circle': None,
  'Ridged Circle': None,
  'Shallow Ridged Circle': None},
 'Scoops': {'Cracked Kite': None,
  'Scoop': None,
  'Spear': None,
  'Tunnel': None,
  'Volcano': None},
 'Smooth': {'Caldera Diamond': None,
  'Cheeky': None,
  'Raised Rectangle': None,
  'Smooth': None,
  'Smooth Arrow': None,
  'Smooth circle': None,
  'Smooth Extended Trident': None,
  'Smooth Nubbed': None,
  'Smooth Petal': None,
  'Smooth Scalloped': None,
  'Thumbprint disc': None},
 'Spines': {'Circular tipping spine': None,
  'Fusiform spines': None,
  'Nub Spine': None,
  'Radial Angled Spines': None,
  'Triangular Spines': None},
 'Tridents': {'Big Three Ridge': None,
  'Central Five Ridged Extended Trident': None,
  'Central Ridged Extended Trident': None,
  'Central Seven Ridged Extended Trident': None,
  'Chubby Trident': None,
  'Dagger': None,
  'Eared Trident': None,
  'Extended Central Ridged and Textured Trident': None,
  'Extended Troughed Trident': None,
  'Lobular Trident': None,
  'Lopsided Trident': None,
  'Madeleine Trident': None,
  'Many Ridged Trident': None,
  'Round Bottomed Textured Tulip': None,
  'Round Ridged Trident': None,
  'Round Sided Trident': None,
  'Short Many Ridged Trident': None,
  'Short Troughed Trident': None,
  'Six Ridged Troughed Trident': None,
  'Textured Trident': None,
  'Thin Ridged Trident': None,
  'Trident': None,
  'Trident with One Side Outgrowth': None,
  'Trident with Pointed Base': None,
  'Trident with Rounded Base': None,
  'Two Ridged Trident': None,
  'Two Ridged Troughed Trident': None,
  'Wavey Trident': None,
  'Wide Thin Ridged Trident': None,
  'Wrapped Trident': None},
 'Wedges': {'Elongated Asymmetrical': None,
  'Pear Shaped Wedge': None,
  'Skinny Pear Shaped Wedge': None,
  'Two Big Lobes': None,
  'Two Ridged Wedge': None,
  'Two Sectioned Wedge': None,
  'Wedged Branching Crown': None,
  'Whale Blow': None},
 'Cat ears': None,
 'Circular minor-curve spine': None,
 'Convergent trident': None,
 'Diverging three-ridged fan': None,
 'Double-U': None,
 'Even ridged flipper': None,
 'Extended Claws': None,
 'Extended single ridged arrowhead': None,
 'Extended single ridged spine': None,
 'Lopsided trident 2': None,
 'NA': None,
 'New lopsided trident': None,
 'Odd-ridged flipper': None,
 'Ridged diamond morph 1': None,
 'Short cusped smooth trident': None,
 'Smooth oval': None,
 'SOS': None,
 'Stretched trident': None,
 'Stubby Claws': None,
 'Troughed trident with ridge outgrowth': None,
 'z': None}

In [ ]:
#cats['Type'] = list(types['dropdown menu'])
#cats['NestedType'] = nested